### ISSUE TITLE
Using incorrect comment for file type sometimes

### ISSUE THREAD

**Issue by cjavdev** [bakks/butterfish.nvim#2]
This might be a problem with my vim-commentary setup. (Just switched from tcomment_vim)

When I try `BFExplain` on `puts "testing"` it adds the explanation with `//` but when I explain a ruby method it starts comments with `#` as expected. 

https://share.descript.com/view/Llq2ELqK7xd?transcript=false

**Comment by bakks** [comment]
Just took a look, apparently I wasn't including the filetype in the prompt for the explain command, so a lot of code was a strong enough hint but `puts "testing"` wasn't. Added a commit here that should help: https://github.com/bakks/butterfish.nvim/commit/93aa35903ac6114f4bb13ff7330e42c0df345bb7

**Comment by bakks** [comment]
Closing for now, let me know if this crops up again

**Comment by cjavdev** [comment]
Works! Thanks for the fast turnaround.
