### ISSUE TITLE
Invalid key error

### ISSUE THREAD

**Issue by ariel-frischer** [bakks/butterfish.nvim#3]
Hey really cool plugin, just getting an error in `reset_status_bar` method. I ran `BFFilePrompt`, and this error occurs after it writes to the file.

Error executing vim.schedule lua callback: .../share/nvim/lazy/butterfish.nvim/lua/butterfish/init.lua:71: invalid key: 
stack traceback:
	[C]: in function 'nvim_set_hl'
	.../share/nvim/lazy/butterfish.nvim/lua/butterfish/init.lua:71: in function 'reset_status_bar'
	.../share/nvim/lazy/butterfish.nvim/lua/butterfish/init.lua:182: in function <.../share/nvim/lazy/butterfish.nvim/lua/butterfish/init.lua:177>
	
Here is the line throwing the error:
```lua
  vim.api.nvim_set_hl(0, butterfish.active_color_group, original_hl)
```

I'm using nvchad + `NVIM v0.9.4`.
Also curious is there a reason to use butterfish rather than open-ai API request?

**Comment by bakks** [comment]
Thanks for error report, let me take a look

**Comment by bakks** [comment]
Ok @ariel-frischer, I just pushed a commit, give it a try. I think this is something different about your environment so I haven't precisely replicated the error, but I think this fix will work, tell me if not!

**Comment by bakks** [comment]
Also explanation of the Butterfish thing:
- It's my CLI tool for using LLMs, so it's familiar, useful, and I can add features I want. It uses OpenAI API.
- If you use butterfish then this shares the auth
- I think a CLI tool is a good LLM interface, i.e. this way you can edit `common.sh` and swap in a different tool, it just needs to print stuff to stdout
- I needed features like "strip out ``` markdown backticks from streaming text" and would rather implement them in something other than Lua

**Comment by ariel-frischer** [comment]
@bakks Seems like its fixed! Thank you!
